// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Drive/DriveWithJoystick.h"
#include "Commands/TeleOp/CubeIntakeCommand.h"
#include "Commands/TeleOp/ToggleSliderUsage.h"
#include "Commands/TogglePot.h"
#include <iostream>
#include "Commands/Autonomous/SetShaftSetpointAuto.h"
#include "Commands/TeleOp/ReleaseRamp.h"
#include "Commands/TeleOp/ReleaseShaft.h"
#include "Commands/TeleOp/Climb.h"
#include "Commands/TeleOp/LiftRamp.h"
#include "Commands/ElevatorDoNothing.h"
#include "Commands/TeleOp/SetShaftSetpointTeleop.h"
#include "Commands/ManualShaftControl.h"

OI::OI() {
	driverJoystick.reset(new frc::Joystick(0));
	buttonBoard.reset(new frc::Joystick(1));

	intakeButton.reset(new frc::JoystickButton(buttonBoard.get(), INTAKE_BUTTON));
	expungeButton.reset(new frc::JoystickButton(buttonBoard.get(), EXPUNGE_BUTTON));
	toggleSliderControl.reset(new frc::JoystickButton(buttonBoard.get(), TOGGLE_SLIDER_BUTTON));
	releaseShaftButton.reset(new frc::JoystickButton(buttonBoard.get(), RELEASE_SHAFT_BUTTON));
	releaseRampButton.reset(new frc::JoystickButton(buttonBoard.get(), RELEASE_RAMP_BUTTON)); //FIXME maybe i dunno
	togglePot.reset(new frc::JoystickButton(buttonBoard.get(), TOGGLE_POT_BUTTON));

	endgameOverride.reset(new frc::JoystickButton(buttonBoard.get(), ENDGAME_OVERRIDE_BUTTON));
	climb.reset(new frc::JoystickButton(buttonBoard.get(), CLIMB_BUTTON));
	rampLift.reset(new frc::JoystickButton(buttonBoard.get(), RAMP_LIFT_BUTTON));

	toggleSliderControl->WhenPressed(new ToggleSliderUsage());
	togglePot->WhenPressed(new TogglePot());

	expungeButton->WhileHeld(new CubeIntakeCommand(false, 0));
	intakeButton->WhileHeld(new CubeIntakeCommand(true, 0));

	releaseShaftButton->WhenPressed(new ReleaseShaft());

	climb->WhileHeld(new Climb());
	rampLift->WhenPressed(new LiftRamp());

}

void OI::ResetElevatorLogic() {
	DriverStation::ReportError("Resetting lights");
	if(!sliderEnabled) {
		DriverStation::ReportError("Doing Nothing");
		GetButtonBoard()->SetOutput(TOGGLE_SLIDER_LED, true);
		Robot::elevator->Disable();
		DriverStation::ReportError("Disabling PID");
	} else {
		GetButtonBoard()->SetOutput(TOGGLE_SLIDER_LED, false);
		if (usePID) {
			GetButtonBoard()->SetOutput(TOGGLE_PID_LED, false);
			DriverStation::ReportError("Using POT");
			Robot::elevator->Enable();
			DriverStation::ReportError("Enabling PID");
		} else {
			GetButtonBoard()->SetOutput(TOGGLE_PID_LED, true);
			DriverStation::ReportError("Using Manual Control");
			Robot::elevator->Disable();
			DriverStation::ReportError("Disabling PID");
		}
	}
	Robot::aesthetics->Update();
}

std::shared_ptr<frc::Joystick> OI::GetDriverJoystick() {
	return driverJoystick;
}

std::shared_ptr<frc::Joystick> OI::GetButtonBoard() {
	return buttonBoard;
}

std::shared_ptr<frc::JoystickButton> OI::GetReleaseRampButton() {
	return releaseRampButton;
}

std::shared_ptr<frc::JoystickButton> OI::GetLiftRampButton() {
	return rampLift;
}

std::shared_ptr<frc::JoystickButton> OI::GetClimbButton() {
	return climb;
}



