// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H


#define INTAKE_BUTTON 1
#define EXPUNGE_BUTTON 2
#define TOGGLE_SLIDER_BUTTON 3
#define RELEASE_SHAFT_BUTTON 4
#define RELEASE_RAMP_BUTTON 9
#define TOGGLE_POT_BUTTON 8
#define ENDGAME_OVERRIDE_BUTTON 5
#define CLIMB_BUTTON 6
#define POT_REZERO_BUTTON 7

#define CLIMB_LED 1
#define ZERO_BOTTOM_LED 2

#define TOGGLE_PID_LED 3
#define TOGGLE_SLIDER_LED 4

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	std::shared_ptr<frc::Joystick> driverJoystick;
	std::shared_ptr<frc::Joystick> buttonBoard;
	std::shared_ptr<frc::JoystickButton> intakeButton;
	std::shared_ptr<frc::JoystickButton> expungeButton;
	std::shared_ptr<frc::JoystickButton> toggleSliderControl;
	std::shared_ptr<frc::JoystickButton> togglePot;

	std::shared_ptr<frc::JoystickButton> releaseShaftButton;
	std::shared_ptr<frc::JoystickButton> releaseRampButton;

	std::shared_ptr<frc::JoystickButton> endgameOverride;
	std::shared_ptr<frc::JoystickButton> climb;
	std::shared_ptr<frc::JoystickButton> potRezeroLift;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
	void ResetElevatorLogic();
	bool sliderEnabled = false;
	bool usePID = true;
	bool setBottom = false;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> GetDriverJoystick();
	std::shared_ptr<frc::Joystick> GetButtonBoard();
	std::shared_ptr<frc::JoystickButton> GetReleaseRampButton();
	std::shared_ptr<frc::JoystickButton> GetLiftRampButton();
	std::shared_ptr<frc::JoystickButton> GetClimbButton();



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
