// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	std::shared_ptr<frc::Joystick> driverJoystick;
	std::shared_ptr<frc::Joystick> buttonBoard;
	std::shared_ptr<frc::JoystickButton> intakeButton;
	std::shared_ptr<frc::JoystickButton> expungeButton;
	std::shared_ptr<frc::JoystickButton> toggleSliderControl;
	std::shared_ptr<frc::JoystickButton> togglePot;

	std::shared_ptr<frc::JoystickButton> releaseShaftButton;
	std::shared_ptr<frc::JoystickButton> releaseRampButton;

	std::shared_ptr<frc::JoystickButton> endgameOverride;
	std::shared_ptr<frc::JoystickButton> climb;
	std::shared_ptr<frc::JoystickButton> rampLift;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
	void ResetElevatorLogic();
	bool sliderEnabled = false;
	bool usePID = true;

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<frc::Joystick> GetDriverJoystick();
	std::shared_ptr<frc::Joystick> GetButtonBoard();
	std::shared_ptr<frc::JoystickButton> GetReleaseRampButton();
	std::shared_ptr<frc::JoystickButton> GetLiftRampButton();
	std::shared_ptr<frc::JoystickButton> GetClimbButton();



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
